[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
fnv = "1.0.7"
impl_ops = "0.1.1"
itertools = "0.14.0"
paste = "1.0.15"
tuple-map = "0.4.0"

[lints.clippy]
ptr_arg = "allow"
